name: Build Images ZIP

on:
  push:
    paths:
      - 'worlds/plugins/images/**'
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  build-images-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create images ZIP
        run: |
          cd worlds/plugins
          zip -r images.zip images/
          
      - name: Upload images.zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: images-zip
          path: worlds/plugins/images.zip
          retention-days: 90
          
      - name: Commit and push images.zip to repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          cp worlds/plugins/images.zip .
          git add images.zip
          git commit -m "Auto-update images.zip [skip ci]" || exit 0
          git push